

version: "3"
services:
  react:
   tty: true
   build:
     context: ./frontend
     dockerfile: Dockerfile
   ports: 
    - 3000:3000


  flask:
   build:
     context: ./backend
     dockerfile: Dockerfile
   ports: 
    - 5000:5000

